# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_been_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
