# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_message_has_been_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='has_been_sent',
            new_name='email_has_been_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='sms_has_been_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
