# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 15:15
from __future__ import unicode_literals

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(validators=[community.models.validate_future]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(validators=[community.models.validate_future]),
        ),
    ]
