# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_groupprofile_notificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
