# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_groupprofile_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupProfile',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='notificationprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationProfile',
        ),
    ]
