# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20160419_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(blank=True, to='community.Event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(max_length=128),
        ),
    ]
