# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20160419_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_source',
            field=models.CharField(default='facebook', max_length=64),
        ),
    ]
