# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_event_external_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='group',
            new_name='facebook_group',
        ),
    ]
