# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20160421_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Default Description', max_length=4000),
            preserve_default=False,
        ),
    ]
